[de APP_INFO
  ("name"      "picolisp-sqlite")
  ("version"   "0.1.0")
  ("summary"   "SQLite3 interface written in PicoLisp")
  ("source"    "https://github.com/aw/picolisp-sqlite")
  ("author"    "Alexander Williams")
  ("license"   "MIT")
  ("copyright" "(c) 2023 Alexander Williams, On-Prem, https://on-premises.com")
  ("requires"
    ("picolisp-unit"   "v3.1.0"      "https://github.com/aw/picolisp-unit.git") ]
